### ISSUE TITLE
Test failures in test_c_locale_coercion

### ISSUE THREAD

**Issue by kadler** [kadler/cpython#21]
Lots of test failures like

```
======================================================================
FAIL: test_LC_ALL_set_to_C (test.test_c_locale_coercion.LocaleCoercionTests) (default_locale=True, PYTHONCOERCECLOCALE=None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_c_locale_coercion.py", line 336, in _check_c_locale_coercion
    self._check_child_encoding_details(base_var_dict,
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_c_locale_coercion.py", line 226, in _check_child_encoding_details
    self.assertEqual(encoding_details, expected_details)
AssertionError: {'fsencoding': 'iso8859-1', 'stdin_info': 'iso8859-1:surr[140 chars] 'C'} != {'fsencoding': 'ascii', 'stdin_info': 'ascii:surrogateesc[124 chars] 'C'}
- {'fsencoding': 'iso8859-1',
?                  ^^^^^^^^

+ {'fsencoding': 'ascii',
?                 +++ ^

   'lang': '',
   'lc_all': 'C',
   'lc_ctype': '',
-  'stderr_info': 'iso8859-1:backslashreplace',
?                   ^^^^^^^^

+  'stderr_info': 'ascii:backslashreplace',
?                  +++ ^

-  'stdin_info': 'iso8859-1:surrogateescape',
?                  ^^^^^^^^

+  'stdin_info': 'ascii:surrogateescape',
?                 +++ ^

-  'stdout_info': 'iso8859-1:surrogateescape'}
?                   ^^^^^^^^

+  'stdout_info': 'ascii:surrogateescape'}
?                  +++ ^
```

This is because AIX C locale is in iso8859-1, not ascii. Tests already handle AIX, so we can just glom on to that for os400.

**Comment by kadler** [comment]
Same issue affects test_utf8_mode:

```
======================================================================
FAIL: test_cmd_line (test.test_utf8_mode.UTF8ModeTests) (LC_ALL='C')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_utf8_mode.py", line 236, in test_cmd_line
    check('utf8=0', [c_arg], LC_ALL=loc)
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_utf8_mode.py", line 221, in check
    self.assertEqual(args, ascii(expected), out)
AssertionError: "['h\\xc3\\xa9\\xe2\\x82\\xac']" != "['h\\udcc3\\udca9\\udce2\\udc82\\udcac']"
- ['h\xc3\xa9\xe2\x82\xac']
+ ['h\udcc3\udca9\udce2\udc82\udcac']
 : ISO8859-1:['h\xc3\xa9\xe2\x82\xac']

======================================================================
FAIL: test_cmd_line (test.test_utf8_mode.UTF8ModeTests) (LC_ALL='POSIX')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_utf8_mode.py", line 236, in test_cmd_line
    check('utf8=0', [c_arg], LC_ALL=loc)
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_utf8_mode.py", line 221, in check
    self.assertEqual(args, ascii(expected), out)
AssertionError: "['h\\xc3\\xa9\\xe2\\x82\\xac']" != "['h\\udcc3\\udca9\\udce2\\udc82\\udcac']"
- ['h\xc3\xa9\xe2\x82\xac']
+ ['h\udcc3\udca9\udce2\udc82\udcac']
 : ISO8859-1:['h\xc3\xa9\xe2\x82\xac']
```
