### ISSUE TITLE
Test failures in test_socket

### ISSUE THREAD

**Issue by kadler** [kadler/cpython#26]
Lots of test failures like
```
======================================================================
ERROR: testGetaddrinfo (test.test_socket.GeneralModuleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_socket.py", line 1448, in testGetaddrinfo
    socket.getaddrinfo('localhost', 80)
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 10] Socket type not supported

======================================================================
ERROR: testRecvmsgLongAncillaryBuf (test.test_socket.RecvmsgUDPTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_socket.py", line 2982, in testRecvmsgLongAncillaryBuf
    msg, ancdata, flags, addr = self.doRecvmsg(self.serv_sock,
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_socket.py", line 2557, in doRecvmsg
    result = sock.recvmsg(bufsize, *args)
OSError: [Errno 22] Invalid argument
```

Probably some tests which are ignored on AIX.

**Comment by kadler** [comment]
This test failure is specific to IBM i, though:
```
======================================================================
FAIL: test_getnameinfo_ipv6_scopeid_symbolic (test.test_socket.GeneralModuleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_socket.py", line 1732, in test_getnameinfo_ipv6_scopeid_symbolic
    self.assertEqual(nameinfo, ('ff02::1de:c0:face:8d%' + test_interface, '1234'))
AssertionError: Tuples differ: ('ff02::1de:c0:face:8d', '1234') != ('ff02::1de:c0:face:8d%*LOOPBACK', '1234')

First differing element 0:
'ff02::1de:c0:face:8d'
'ff02::1de:c0:face:8d%*LOOPBACK'

- ('ff02::1de:c0:face:8d', '1234')
+ ('ff02::1de:c0:face:8d%*LOOPBACK', '1234')
?                       ++++++++++
```

**Comment by abmusse** [comment]
> socket.gaierror: [Errno 10] Socket type not supported

The above error was caused by IBM i sockets bug. Need to apply PTF [MF65685](https://www.ibm.com/support/pages/ptf/MF65685) for fix.

**Comment by abmusse** [comment]
> test_getnameinfo_ipv6_scopeid_symbolic

Above test case should be skipped on IBM i as it is also skipped on AIX. https://github.com/kadler/cpython/blob/2c1350b36ff0169b4c0903aa832925913908e15e/Lib/test/test_socket.py#L1726
