### ISSUE TITLE
Test failures in test_io

### ISSUE THREAD

**Issue by kadler** [kadler/cpython#31]
```
======================================================================
ERROR: test_large_file_ops (test.test_io.CIOTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_io.py", line 610, in test_large_file_ops
    self.large_file_ops(f)
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_io.py", line 387, in large_file_ops
    self.assertEqual(f.seek(self.LARGE), self.LARGE)
OSError: [Errno 127] Value too large to be stored in data type

======================================================================
ERROR: test_large_file_ops (test.test_io.PyIOTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_io.py", line 610, in test_large_file_ops
    self.large_file_ops(f)
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_io.py", line 387, in large_file_ops
    self.assertEqual(f.seek(self.LARGE), self.LARGE)
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/_pyio.py", line 1710, in seek
    return os.lseek(self._fd, pos, whence)
OSError: [Errno 127] Value too large to be stored in data type
```

**Comment by abmusse** [comment]
This looks to have been caused by SLIC not adding the `O_LARGEFILE` flag in the 64-bit syscalls

```python
>>> import os
>>> TESTFN = "{}_{}_tmp".format("@test", os.getpid())
>>> LARGE = 2**31
>>> with open(TESTFN, "w+b", 0) as f:
...     assert f.readable()
...     assert f.writable()
...     ret = f.seek(LARGE)
...     print(f"ret is: {ret} , type is: {type(ret)}")
...     print(f"LARGE is: {LARGE}, type is: {type(LARGE)}")
... 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
OSError: [Errno 127] Value too large to be stored in data type

```
Need to apply the following PTFS for fix:
```
R720 MF65149 PTF
R730 MF65148 PTF
```
