### ISSUE TITLE
Test failures in test_grp

### ISSUE THREAD

**Issue by kadler** [kadler/cpython#38]
```
======================================================================
ERROR: test_errors (test.test_grp.GroupDatabaseTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/test_grp.py", line 67, in test_errors
    fakename = allnames[namei]
IndexError: list index out of range
```

**Comment by abmusse** [comment]
This issue is looks to originate from a lack of groups setup on the build system.

Extracting the surrounding code in `cpyton/Lib/test/test_grp.py , line 67` into a script:

```python
#! /QOpenSys/pkgs/bin/python

import grp

bynames = {}
bygids = {}
for (n, p, g, mem) in grp.getgrall():
    if not n or n == '+':
        continue # skip NIS entries etc.
    bynames[n] = g
    bygids[g] = n

allnames = list(bynames.keys())
print(f'allnames = {allnames}')
namei = 0
fakename = allnames[namei]
print(f'fakename = {fakename}')
```
Then running the script on the build machine yields the same error:

```sh
$ ./grp_all_example.py 
allnames = []
Traceback (most recent call last):
  File "./grp_all_example.py", line 16, in <module>
    fakename = allnames[namei]
IndexError: list index out of range
```

But running the script on system with some groups setup script it successful

```sh
$ ./grp_all_example.py 
allnames = ['grp1', 'grp2', 'qsecofr', 'nobody', 'group', 'grp3', 'pygrp1']
fakename = grp1
```

**Comment by kadler** [comment]
Yeah, out of the box, there's no groups on IBM i.

**Comment by abmusse** [comment]
Thoughts on adding a group as part of the `test` stage (before) we invoke the test suite?

**Comment by kadler** [comment]
No, that would require `*SECADM` special authority to create the group. Ideally, the user running Python tests should not have any special authorities.
