### ISSUE TITLE
Test crash in test_multiprocessing_fork

### ISSUE THREAD

**Issue by kadler** [kadler/cpython#7]
```
0:04:12 [ 38/420/3] test_multiprocessing_fork crashed (Exit code -4)
Fatal Python error: Illegal instruction

Current thread 0x0000000000000001 (most recent call first):
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/_test_multiprocessing.py", line 90 in _resource_unlink
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/_test_multiprocessing.py", line 5054 in test_resource_tracker
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/case.py", line 616 in _callTestMethod
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/case.py", line 659 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/case.py", line 719 in __call__
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 122 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 84 in __call__
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 122 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 84 in __call__
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 122 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 84 in __call__
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/runner.py", line 176 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/support/__init__.py", line 2079 in _run_suite
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/support/__init__.py", line 2201 in run_unittest
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 209 in _test_module
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 234 in _runtest_inner2
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 270 in _runtest_inner
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 140 in _runtest
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 193 in runtest
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest_mp.py", line 80 in run_tests_worker
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/main.py", line 654 in _main
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/main.py", line 634 in main
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/main.py", line 712 in main
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/regrtest.py", line 43 in _main
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/regrtest.py", line 47 in <module>
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/runpy.py", line 86 in _run_code
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/runpy.py", line 193 in _run_module_as_main
```

**Comment by kadler** [comment]
Seems to affect test_multiprocessing_spawn as well:

```
0:16:06 [169/420/15] test_multiprocessing_spawn crashed (Exit code -4)
Fatal Python error: Illegal instruction

Current thread 0x0000000000000001 (most recent call first):
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/_test_multiprocessing.py", line 90 in _resource_unlink
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/_test_multiprocessing.py", line 5054 in test_resource_tracker
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/case.py", line 616 in _callTestMethod
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/case.py", line 659 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/case.py", line 719 in __call__
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 122 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 84 in __call__
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 122 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 84 in __call__
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 122 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 84 in __call__
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/runner.py", line 176 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/support/__init__.py", line 2079 in _run_suite
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/support/__init__.py", line 2201 in run_unittest
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 209 in _test_module
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 234 in _runtest_inner2
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 270 in _runtest_inner
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 140 in _runtest
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 193 in runtest
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest_mp.py", line 80 in run_tests_worker
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/main.py", line 654 in _main
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/main.py", line 634 in main
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/main.py", line 712 in main
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/regrtest.py", line 43 in _main
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/regrtest.py", line 47 in <module>
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/runpy.py", line 86 in _run_code
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/runpy.py", line 193 in _run_module_as_main
```

**Comment by kadler** [comment]
And in test_multiprocessing_forkserver

```
0:33:18 [360/420/33] test_multiprocessing_forkserver crashed (Exit code -4)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/multiprocessing/forkserver.py", line 262, in main
    fds = reduction.recvfds(s, MAXFDS_TO_SEND + 1)
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/multiprocessing/reduction.py", line 157, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_SPACE(bytes_size))
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/multiprocessing/forkserver.py", line 262, in main
    fds = reduction.recvfds(s, MAXFDS_TO_SEND + 1)
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/multiprocessing/reduction.py", line 157, in recvfds
    msg, ancdata, flags, addr = sock.recvmsg(1, socket.CMSG_SPACE(bytes_size))
OSError: [Errno 22] Invalid argument
Fatal Python error: Illegal instruction

Current thread 0x0000000000000001 (most recent call first):
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/_test_multiprocessing.py", line 90 in _resource_unlink
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/_test_multiprocessing.py", line 5054 in test_resource_tracker
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/case.py", line 616 in _callTestMethod
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/case.py", line 659 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/case.py", line 719 in __call__
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 122 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 84 in __call__
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 122 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 84 in __call__
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 122 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/suite.py", line 84 in __call__
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/unittest/runner.py", line 176 in run
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/support/__init__.py", line 2079 in _run_suite
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/support/__init__.py", line 2201 in run_unittest
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 209 in _test_module
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 234 in _runtest_inner2
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 270 in _runtest_inner
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 140 in _runtest
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest.py", line 193 in runtest
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/runtest_mp.py", line 80 in run_tests_worker
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/main.py", line 654 in _main
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/main.py", line 634 in main
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/libregrtest/main.py", line 712 in main
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/regrtest.py", line 43 in _main
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/test/regrtest.py", line 47 in <module>
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/runpy.py", line 86 in _run_code
  File "/QOpenSys/jenkins/workspace/cpython_sem-fix/Lib/runpy.py", line 193 in _run_module_as_main
```
